PRAGMA foreign_keys = ON;

INSERT INTO curriculum_versions (id, version_key, version_number, status, published_at) VALUES
  ('cv-v1', 'hangeuloo-foundation-v1', 1, 'active', CURRENT_TIMESTAMP);

INSERT INTO curriculum_branches (id, curriculum_version_id, branch_key, title_id, title_en, description_id, description_en, availability, display_order) VALUES
  ('br-conversation', 'cv-v1', 'conversation', 'Percakapan Sehari-hari', 'Everyday Conversation', 'Sapa, perkenalkan diri, dan bicarakan hal sederhana dengan sopan.', 'Greet people, introduce yourself, and talk about simple everyday things politely.', 'available', 1),
  ('br-travel', 'cv-v1', 'travel', 'Perjalanan', 'Travel', 'Transportasi, penginapan, makanan, belanja, dan arah jalan.', 'Transport, lodging, food, shopping, and directions.', 'coming_soon', 2),
  ('br-work', 'cv-v1', 'work', 'Pekerjaan', 'Work', 'Dasar profesional dan persiapan wawancara kerja.', 'Professional basics and job interview preparation.', 'coming_soon', 3),
  ('br-topik', 'cv-v1', 'topik', 'Persiapan TOPIK', 'TOPIK preparation', 'Latihan format ujian TOPIK akan segera hadir.', 'TOPIK exam preparation is coming soon.', 'coming_soon', 4);

INSERT INTO curriculum_milestones (id, curriculum_version_id, milestone_key, title_id, title_en, description_id, description_en, milestone_order) VALUES
  ('ms-vowels', 'cv-v1', 'basic-vowels', 'Vokal dasar', 'Basic vowels', 'Kenali bentuk dan bunyi vokal Hangul yang penting.', 'Recognize the shapes and sounds of essential Hangul vowels.', 1),
  ('ms-consonants-1', 'cv-v1', 'first-consonants', 'Konsonan pertama', 'First consonants', 'Pelajari konsonan pertama dan bentuk blok suku kata.', 'Learn the first consonants and how syllable blocks form.', 2),
  ('ms-consonants-2', 'cv-v1', 'remaining-consonants', 'Konsonan lanjutan', 'More consonants', 'Lengkapi semua konsonan dasar Hangul.', 'Complete the full set of basic Hangul consonants.', 3),
  ('ms-batchim', 'cv-v1', 'batchim', 'Batchim', 'Final consonants', 'Pahami tujuh bunyi akhir dan peralihan suara dasar.', 'Master the seven final sounds and basic sound carryover.', 4),
  ('ms-fluency', 'cv-v1', 'decoding-fluency', 'Kelancaran membaca', 'Decoding fluency', 'Buktikan kamu bisa membaca blok suku kata baru sendiri.', 'Prove you can read unfamiliar syllable blocks on your own.', 5);

INSERT INTO curriculum_nodes (id, curriculum_version_id, node_key, node_type, lesson_role, milestone_id, branch_id, title_id, title_en, description_id, description_en, estimated_minutes, xp_reward, display_order) VALUES
  ('f-vowels', 'cv-v1', 'f-vowels', 'lesson', 'core', 'ms-vowels', NULL, 'Vokal dasar', 'Basic vowels', 'Kenali bentuk dan bunyi sepuluh vokal dasar.', 'Recognize the shapes and sounds of the ten basic vowels.', 7, 25, 1),
  ('f-check-vowels', 'cv-v1', 'f-check-vowels', 'check', NULL, 'ms-vowels', NULL, 'Cek vokal', 'Vowel check', 'Periksa pengenalan bentuk dan bunyi vokal.', 'Check vowel recognition and sounds.', 3, 0, 2),
  ('f-remediation-vowels', 'cv-v1', 'f-remediation-vowels', 'remediation', 'remediation', 'ms-vowels', NULL, 'Ulasan vokal', 'Vowel review', 'Ulangi vokal yang masih membingungkan.', 'Review the vowels that still feel tricky.', 4, 0, 3),
  ('f-consonants-1', 'cv-v1', 'f-consonants-1', 'lesson', 'core', 'ms-consonants-1', NULL, 'Konsonan pertama', 'First consonants', 'Pelajari konsonan pertama dan baca blok sederhana.', 'Learn the first consonants and read simple blocks.', 7, 25, 4),
  ('f-check-consonants-1', 'cv-v1', 'f-check-consonants-1', 'check', NULL, 'ms-consonants-1', NULL, 'Cek konsonan pertama', 'First consonants check', 'Periksa konsonan pertama yang sudah dipelajari.', 'Check the first consonants you learned.', 3, 0, 5),
  ('f-remediation-consonants-1', 'cv-v1', 'f-remediation-consonants-1', 'remediation', 'remediation', 'ms-consonants-1', NULL, 'Ulasan konsonan pertama', 'First consonants review', 'Ulangi konsonan pertama yang masih sulit.', 'Review the first consonants that still feel hard.', 4, 0, 6),
  ('f-consonants-2', 'cv-v1', 'f-consonants-2', 'lesson', 'core', 'ms-consonants-2', NULL, 'Konsonan lanjutan', 'More consonants', 'Lengkapi konsonan dasar Hangul yang tersisa.', 'Complete the remaining basic Hangul consonants.', 8, 25, 7),
  ('f-check-consonants-2', 'cv-v1', 'f-check-consonants-2', 'check', NULL, 'ms-consonants-2', NULL, 'Cek konsonan lanjutan', 'More consonants check', 'Periksa semua konsonan dasar.', 'Check all the basic consonants.', 3, 0, 8),
  ('f-remediation-consonants-2', 'cv-v1', 'f-remediation-consonants-2', 'remediation', 'remediation', 'ms-consonants-2', NULL, 'Ulasan konsonan lanjutan', 'More consonants review', 'Ulangi konsonan yang masih membingungkan.', 'Review the consonants that still confuse you.', 4, 0, 9),
  ('f-batchim', 'cv-v1', 'f-batchim', 'lesson', 'core', 'ms-batchim', NULL, 'Batchim', 'Final consonants', 'Kenali tujuh bunyi akhir dan peralihan suara.', 'Recognize the seven final sounds and sound carryover.', 7, 25, 10),
  ('f-check-batchim', 'cv-v1', 'f-check-batchim', 'check', NULL, 'ms-batchim', NULL, 'Cek batchim', 'Final consonants check', 'Periksa pemahaman bunyi akhir.', 'Check your understanding of final sounds.', 3, 0, 11),
  ('f-remediation-batchim', 'cv-v1', 'f-remediation-batchim', 'remediation', 'remediation', 'ms-batchim', NULL, 'Ulasan batchim', 'Final consonants review', 'Ulangi bunyi akhir yang masih sulit.', 'Review the final sounds that still feel hard.', 4, 0, 12),
  ('f-check-fluency', 'cv-v1', 'f-check-fluency', 'check', NULL, 'ms-fluency', NULL, 'Cek kelancaran membaca', 'Reading fluency check', 'Buktikan kamu bisa membaca Hangul baru.', 'Prove you can read unfamiliar Hangul.', 8, 0, 13),
  ('f-remediation-fluency', 'cv-v1', 'f-remediation-fluency', 'remediation', 'remediation', 'ms-fluency', NULL, 'Ulasan kelancaran', 'Fluency review', 'Latihan membaca kata yang masih sulit.', 'Practice reading the words that still feel hard.', 6, 0, 14),
  ('branch-choice', 'cv-v1', 'branch-choice', 'branch_choice', NULL, NULL, NULL, 'Pilih jalurmu', 'Choose your path', 'Pilih topik kontekstual untuk dipelajari berikutnya.', 'Choose the contextual topic to learn next.', 2, 0, 15),
  ('c-1-greetings', 'cv-v1', 'c-1-greetings', 'lesson', 'core', NULL, 'br-conversation', 'Salam', 'Greetings', 'Sapa orang lain dengan ungkapan Korea yang sopan.', 'Greet people with polite Korean expressions.', 6, 20, 16),
  ('c-1-practice', 'cv-v1', 'c-1-practice', 'practice', NULL, NULL, 'br-conversation', 'Latihan salam', 'Greetings practice', 'Latih kembali salam yang baru dipelajari.', 'Practice the greetings you just learned.', 4, 0, 17),
  ('c-2-intro', 'cv-v1', 'c-2-intro', 'lesson', 'core', NULL, 'br-conversation', 'Perkenalan diri', 'Introducing yourself', 'Perkenalkan nama dan identitas dasarmu.', 'Introduce your name and basic identity.', 7, 20, 18),
  ('c-2-practice', 'cv-v1', 'c-2-practice', 'practice', NULL, NULL, 'br-conversation', 'Latihan perkenalan', 'Introduction practice', 'Latih pola perkenalan diri.', 'Practice the self-introduction patterns.', 4, 0, 19),
  ('c-3-questions', 'cv-v1', 'c-3-questions', 'lesson', 'core', NULL, 'br-conversation', 'Pertanyaan dasar', 'Basic questions', 'Ajukan dan jawab pertanyaan pribadi sederhana.', 'Ask and answer simple personal questions.', 7, 20, 20),
  ('c-3-practice', 'cv-v1', 'c-3-practice', 'practice', NULL, NULL, 'br-conversation', 'Latihan pertanyaan', 'Questions practice', 'Latih pertanyaan dan jawaban dasar.', 'Practice basic questions and answers.', 4, 0, 21),
  ('c-4-likes', 'cv-v1', 'c-4-likes', 'lesson', 'core', NULL, 'br-conversation', 'Suka dan tidak suka', 'Likes and dislikes', 'Ungkapkan kesukaan dan ketidaksukaan.', 'Express likes and dislikes.', 7, 20, 22),
  ('c-4-practice', 'cv-v1', 'c-4-practice', 'practice', NULL, NULL, 'br-conversation', 'Latihan kesukaan', 'Likes practice', 'Latih ungkapan suka dan tidak suka.', 'Practice expressing likes and dislikes.', 4, 0, 23),
  ('c-5-dialogue', 'cv-v1', 'c-5-dialogue', 'lesson', 'core', NULL, 'br-conversation', 'Dialog singkat', 'A short dialogue', 'Gabungkan semuanya dalam dialog perkenalan singkat.', 'Combine everything into a short meet-and-greet.', 7, 20, 24),
  ('c-5-practice', 'cv-v1', 'c-5-practice', 'practice', NULL, NULL, 'br-conversation', 'Latihan dialog', 'Dialogue practice', 'Latih dialog perkenalan dari awal sampai akhir.', 'Practice the full meet-and-greet dialogue.', 4, 0, 25),
  ('c-6-check', 'cv-v1', 'c-6-check', 'check', NULL, NULL, 'br-conversation', 'Cek percakapan', 'Conversation checkpoint', 'Buktikan kamu bisa berkenalan dalam bahasa Korea.', 'Prove you can meet someone in Korean.', 8, 0, 26),
  ('c-6-remediation', 'cv-v1', 'c-6-remediation', 'remediation', 'remediation', NULL, 'br-conversation', 'Ulasan percakapan', 'Conversation review', 'Ulangi bagian percakapan yang masih sulit.', 'Review the conversation parts that still feel hard.', 6, 0, 27);

INSERT INTO curriculum_prerequisites (node_id, prerequisite_node_id, required_outcome) VALUES
  ('f-check-vowels', 'f-vowels', 'completed'),
  ('f-remediation-vowels', 'f-check-vowels', 'failed'),
  ('f-consonants-1', 'f-check-vowels', 'passed'),
  ('f-check-consonants-1', 'f-consonants-1', 'completed'),
  ('f-remediation-consonants-1', 'f-check-consonants-1', 'failed'),
  ('f-consonants-2', 'f-check-consonants-1', 'passed'),
  ('f-check-consonants-2', 'f-consonants-2', 'completed'),
  ('f-remediation-consonants-2', 'f-check-consonants-2', 'failed'),
  ('f-batchim', 'f-check-consonants-2', 'passed'),
  ('f-check-batchim', 'f-batchim', 'completed'),
  ('f-remediation-batchim', 'f-check-batchim', 'failed'),
  ('f-check-fluency', 'f-check-batchim', 'passed'),
  ('f-remediation-fluency', 'f-check-fluency', 'failed'),
  ('branch-choice', 'f-check-fluency', 'passed'),
  ('c-1-greetings', 'branch-choice', 'branch_selected'),
  ('c-1-practice', 'c-1-greetings', 'completed'),
  ('c-2-intro', 'c-1-practice', 'completed'),
  ('c-2-practice', 'c-2-intro', 'completed'),
  ('c-3-questions', 'c-2-practice', 'completed'),
  ('c-3-practice', 'c-3-questions', 'completed'),
  ('c-4-likes', 'c-3-practice', 'completed'),
  ('c-4-practice', 'c-4-likes', 'completed'),
  ('c-5-dialogue', 'c-4-practice', 'completed'),
  ('c-5-practice', 'c-5-dialogue', 'completed'),
  ('c-6-check', 'c-5-practice', 'completed'),
  ('c-6-remediation', 'c-6-check', 'failed');

INSERT INTO curriculum_node_items (id, node_id, type, korean_text, romanization, translation_id, translation_en, pronunciation_id, pronunciation_en, explanation_id, explanation_en, example_ko, example_id, example_en, vocabulary_id, item_order) VALUES
  ('fv-1', 'f-vowels', 'character', 'ㅏ', 'a', 'Vokal "a"', 'The vowel "a"', 'Buka mulut dengan rileks seperti "a" pada kata "apa".', 'Open your mouth naturally, like "a" in "father".', 'Garis pendek mengarah ke kanan dan diletakkan di kanan konsonan.', 'The short stroke points right and sits to the right of a consonant.', '가 · 나 · 다', 'Bunyi a pada ga, na, dan da.', 'The a sound in ga, na, and da.', NULL, 1),
  ('fv-2', 'f-vowels', 'character', 'ㅓ', 'eo', 'Vokal "eo"', 'The vowel "eo"', 'Ucapkan bunyi di antara "o" dan "a" dengan rahang rileks.', 'Make an open "uh" sound with a relaxed jaw.', 'Garis pendek mengarah ke kiri dan diletakkan di kanan konsonan.', 'The short stroke points left and sits to the right of a consonant.', '거 · 너 · 더', 'Bunyi eo pada geo, neo, dan deo.', 'The eo sound in geo, neo, and deo.', NULL, 2),
  ('fv-3', 'f-vowels', 'character', 'ㅗ', 'o', 'Vokal "o"', 'The vowel "o"', 'Bulatkan bibir tanpa memanjangkan bunyinya.', 'Round your lips without stretching the sound.', 'Vokal horizontal ini diletakkan di bawah konsonan.', 'This horizontal vowel is placed below a consonant.', '고 · 노 · 도', 'Bunyi o pada go, no, dan do.', 'The o sound in go, no, and do.', NULL, 3),
  ('fv-4', 'f-vowels', 'character', 'ㅜ', 'u', 'Vokal "u"', 'The vowel "u"', 'Bulatkan bibir seperti mengucapkan "u".', 'Round your lips like the "oo" in "moon".', 'Garis pendek mengarah ke bawah dan diletakkan di bawah konsonan.', 'The short stroke points down and sits below a consonant.', '구 · 누 · 두', 'Bunyi u pada gu, nu, dan du.', 'The u sound in gu, nu, and du.', NULL, 4),
  ('fv-5', 'f-vowels', 'character', 'ㅣ', 'i', 'Vokal "i"', 'The vowel "i"', 'Tersenyum ringan dan ucapkan "i" dengan jelas.', 'Keep your lips slightly wide and say "ee".', 'Satu garis vertikal yang diletakkan di kanan konsonan.', 'A single vertical line placed to the right of a consonant.', '기 · 니 · 디', 'Bunyi i pada gi, ni, dan di.', 'The i sound in gi, ni, and di.', NULL, 5),
  ('fv-6', 'f-vowels', 'character', 'ㅑ', 'ya', 'Vokal "ya"', 'The vowel "ya"', 'Mulai dengan y ringan lalu lanjutkan ke bunyi a.', 'Begin with a light y and move into the a sound.', 'Dua garis pendek membedakan ㅑ dari ㅏ.', 'Two short strokes distinguish ㅑ from ㅏ.', '야 · 냐 · 랴', 'Bunyi ya pada ya, nya, dan rya.', 'The ya sound in ya, nya, and rya.', NULL, 6),
  ('fv-7', 'f-vowels', 'character', 'ㅕ', 'yeo', 'Vokal "yeo"', 'The vowel "yeo"', 'Mulai dengan y ringan lalu buka ke bunyi eo.', 'Begin with a light y and open into the eo sound.', 'Dua garis pendek mengarah ke kiri.', 'Two short strokes point to the left.', '여 · 녀 · 셔', 'Bunyi yeo pada yeo, nyeo, dan syeo.', 'The yeo sound in yeo, nyeo, and syeo.', NULL, 7),
  ('fv-8', 'f-vowels', 'character', 'ㅛ', 'yo', 'Vokal "yo"', 'The vowel "yo"', 'Bulatkan bibir dan awali dengan y singkat.', 'Round your lips and begin with a short y.', 'Dua garis di atas membedakan ㅛ dari ㅗ.', 'Two upper strokes distinguish ㅛ from ㅗ.', '요 · 교 · 쇼', 'Bunyi yo pada yo, gyo, dan syo.', 'The yo sound in yo, gyo, and syo.', NULL, 8),
  ('fv-9', 'f-vowels', 'character', 'ㅠ', 'yu', 'Vokal "yu"', 'The vowel "yu"', 'Awali dengan y lalu bulatkan bibir untuk u.', 'Begin with y, then round your lips for u.', 'Dua garis ke bawah membedakan ㅠ dari ㅜ.', 'Two downward strokes distinguish ㅠ from ㅜ.', '유 · 규 · 슈', 'Bunyi yu pada yu, gyu, dan syu.', 'The yu sound in yu, gyu, and syu.', NULL, 9),
  ('fv-10', 'f-vowels', 'character', 'ㅡ', 'eu', 'Vokal "eu"', 'The vowel "eu"', 'Ratakan bibir dan tarik bunyi dari bagian belakang mulut.', 'Keep your lips flat and form the sound toward the back of the mouth.', 'Vokal horizontal tunggal ini diletakkan di bawah konsonan.', 'This single horizontal vowel sits below a consonant.', '그 · 느 · 드', 'Bunyi eu pada geu, neu, dan deu.', 'The eu sound in geu, neu, and deu.', NULL, 10),

  ('fc1-1', 'f-consonants-1', 'character', 'ㄱ', 'g/k · giyeok', 'Konsonan g/k', 'The g/k consonant', 'Di awal suku kata terdengar lembut seperti g; di akhir lebih dekat ke k.', 'At the start it is a light g; at the end it is closer to k.', 'Nama huruf ini 기역 (giyeok).', 'Its name is 기역 (giyeok).', '가 · 고 · 국', 'ga, go, dan guk', 'ga, go, and guk', NULL, 1),
  ('fc1-2', 'f-consonants-1', 'character', 'ㄴ', 'n · nieun', 'Konsonan n', 'The n consonant', 'Sentuhkan ujung lidah di belakang gigi atas.', 'Touch the tip of your tongue behind your upper teeth.', 'Nama huruf ini 니은 (nieun).', 'Its name is 니은 (nieun).', '나 · 너 · 눈', 'na, neo, dan nun', 'na, neo, and nun', NULL, 2),
  ('fc1-3', 'f-consonants-1', 'character', 'ㅁ', 'm · mieum', 'Konsonan m', 'The m consonant', 'Tutup kedua bibir seperti bunyi m.', 'Close both lips, just like an m.', 'Nama huruf ini 미음 (mieum).', 'Its name is 미음 (mieum).', '마 · 모 · 몸', 'ma, mo, dan mom', 'ma, mo, and mom', NULL, 3),
  ('fc1-4', 'f-consonants-1', 'character', 'ㅅ', 's · siot', 'Konsonan s', 'The s consonant', 'Di depan ㅣ, bunyinya menjadi lebih dekat ke "sy".', 'Before ㅣ, the sound becomes closer to "sh".', 'Nama huruf ini 시옷 (siot).', 'Its name is 시옷 (siot).', '사 · 소 · 시', 'sa, so, dan si', 'sa, so, and si', NULL, 4),

  ('fc2-1', 'f-consonants-2', 'character', 'ㅎ', 'h · hieut', 'Konsonan h', 'The h consonant', 'Hembuskan udara ringan saat mengucapkan h.', 'Release a light breath as you say h.', 'Nama huruf ini 히읗 (hieut).', 'Its name is 히읗 (hieut).', '하 · 호 · 한', 'ha, ho, dan han', 'ha, ho, and han', NULL, 1),
  ('fc2-2', 'f-consonants-2', 'character', 'ㄷ', 'd/t · digeut', 'Konsonan d/t', 'The d/t consonant', 'Di awal terdengar seperti d ringan dan di akhir seperti t pendek.', 'At the start it is a light d; at the end it is a short t.', 'Nama huruf ini 디귿 (digeut).', 'Its name is 디귿 (digeut).', '다 · 도 · 닫', 'da, do, dan dat', 'da, do, and dat', NULL, 2),
  ('fc2-3', 'f-consonants-2', 'character', 'ㄹ', 'r/l · rieul', 'Konsonan r/l', 'The r/l consonant', 'Di antara vokal terdengar seperti r ringan; di akhir mendekati l.', 'Between vowels it is a light r; at the end it is closer to l.', 'Nama huruf ini 리을 (rieul).', 'Its name is 리을 (rieul).', '라 · 로 · 말', 'ra, ro, dan mal', 'ra, ro, and mal', NULL, 3),
  ('fc2-4', 'f-consonants-2', 'character', 'ㅂ', 'b/p · bieup', 'Konsonan b/p', 'The b/p consonant', 'Awali dengan b lembut; batchim-nya terdengar seperti p pendek.', 'Begin with a soft b; as batchim it sounds like a short p.', 'Nama huruf ini 비읍 (bieup).', 'Its name is 비읍 (bieup).', '바 · 보 · 밥', 'ba, bo, dan bap', 'ba, bo, and bap', NULL, 4),
  ('fc2-5', 'f-consonants-2', 'character', 'ㅇ', 'silent/ng · ieung', 'Konsonan diam/ng', 'The silent/ng consonant', 'Diam di awal suku kata dan berbunyi ng sebagai batchim.', 'It is silent at the start and sounds ng as batchim.', 'Nama huruf ini 이응 (ieung).', 'Its name is 이응 (ieung).', '아 · 오 · 강', 'a, o, dan gang', 'a, o, and gang', NULL, 5),
  ('fc2-6', 'f-consonants-2', 'character', 'ㅈ', 'j · jieut', 'Konsonan j', 'The j consonant', 'Ucapkan j dengan pelepasan udara yang ringan.', 'Say j with a light release of air.', 'Nama huruf ini 지읒 (jieut).', 'Its name is 지읒 (jieut).', '자 · 조 · 집', 'ja, jo, dan jip', 'ja, jo, and jip', NULL, 6),
  ('fc2-7', 'f-consonants-2', 'character', 'ㅊ', 'ch · chieut', 'Konsonan ch', 'The ch consonant', 'Bunyinya seperti j dengan hembusan udara lebih kuat.', 'It sounds like j with a stronger puff of air.', 'Nama huruf ini 치읓 (chieut).', 'Its name is 치읓 (chieut).', '차 · 초 · 춤', 'cha, cho, dan chum', 'cha, cho, and chum', NULL, 7),
  ('fc2-8', 'f-consonants-2', 'character', 'ㅋ', 'k · kieuk', 'Konsonan k', 'The k consonant', 'Lepaskan udara lebih kuat daripada ㄱ.', 'Release more air than with ㄱ.', 'Nama huruf ini 키읔 (kieuk).', 'Its name is 키읔 (kieuk).', '카 · 코 · 키', 'ka, ko, dan ki', 'ka, ko, and ki', NULL, 8),
  ('fc2-9', 'f-consonants-2', 'character', 'ㅌ', 't · tieut', 'Konsonan t', 'The t consonant', 'Lepaskan udara lebih kuat daripada ㄷ.', 'Release more air than with ㄷ.', 'Nama huruf ini 티읕 (tieut).', 'Its name is 티읕 (tieut).', '타 · 토 · 틀', 'ta, to, dan teul', 'ta, to, and teul', NULL, 9),
  ('fc2-10', 'f-consonants-2', 'character', 'ㅍ', 'p · pieup', 'Konsonan p', 'The p consonant', 'Lepaskan udara lebih kuat daripada ㅂ.', 'Release more air than with ㅂ.', 'Nama huruf ini 피읖 (pieup).', 'Its name is 피읖 (pieup).', '파 · 포 · 풀', 'pa, po, dan pul', 'pa, po, and pul', NULL, 10),

  ('fb-1', 'f-batchim', 'word', '한', 'han', 'Satu (bagian dari Korea)', 'One (part of Korea)', 'Mulai dengan h, lanjutkan a, lalu tutup dengan n.', 'Start with h, continue with a, and close with n.', 'ㄴ, ㅁ, dan ㅇ di akhir semuanya berbunyi seperti n atau ng yang lembut.', 'Final ㄴ, ㅁ, and ㅇ all sound like a soft n or ng.', '한국', 'hanguk · Korea', 'hanguk · Korea', NULL, 1),
  ('fb-2', 'f-batchim', 'word', '밥', 'bap', 'Nasi atau makanan', 'Rice or meal', 'Tutup dengan p yang singkat tanpa melepaskan udara.', 'Close with a short p without releasing air.', 'ㄱ, ㄷ, dan ㅂ di akhir bunyinya mengecil menjadi k, t, dan p.', 'Final ㄱ, ㄷ, and ㅂ shrink to k, t, and p.', '밥을 먹어요.', 'Saya makan.', 'I eat a meal.', 8, 2),
  ('fb-3', 'f-batchim', 'word', '물', 'mul', 'Air', 'Water', 'Bunyi ㄹ akhir terdengar singkat, di antara l dan r.', 'The final ㄹ is short and sounds close to l.', 'ㄹ di akhir membuat bunyi l yang lembut.', 'Final ㄹ makes a soft l sound.', '물을 마셔요.', 'Saya minum air.', 'I drink water.', 7, 3),

  ('c1g-1', 'c-1-greetings', 'word', '안녕하세요', 'annyeonghaseyo', 'Halo', 'Hello', 'Tekankan ritme secara merata: an-nyeong-ha-se-yo.', 'Keep an even rhythm: an-nyeong-ha-se-yo.', 'Ungkapan sopan yang aman digunakan hampir di semua situasi.', 'A polite greeting that is safe in almost any situation.', '안녕하세요, 선생님!', 'Halo, Guru!', 'Hello, teacher!', 1, 1),
  ('c1g-2', 'c-1-greetings', 'word', '감사합니다', 'gamsahamnida', 'Terima kasih', 'Thank you', 'Dalam ucapan alami, 합니다 terdengar mendekati hamnida.', 'In natural speech, 합니다 sounds close to hamnida.', 'Gunakan untuk mengucapkan terima kasih dengan sopan atau formal.', 'Use it to say thank you politely or formally.', '정말 감사합니다.', 'Terima kasih banyak.', 'Thank you very much.', 2, 2),
  ('c1g-3', 'c-1-greetings', 'sentence', '만나서 반가워요', 'mannaseo bangawoyo', 'Senang bertemu dengan Anda.', 'Nice to meet you.', 'Sambungkan 만나서 tanpa jeda panjang.', 'Connect 만나서 without a long pause.', 'Ungkapan sopan dan ramah setelah berkenalan.', 'A friendly polite expression after an introduction.', '저도 만나서 반가워요.', 'Saya juga senang bertemu dengan Anda.', 'Nice to meet you too.', NULL, 3),

  ('c2i-1', 'c-2-intro', 'sentence', '저는 학생입니다', 'jeoneun haksaengimnida', 'Saya seorang pelajar.', 'I am a student.', '입니다 diucapkan imnida karena perubahan bunyi alami.', '입니다 is pronounced imnida because of a natural sound change.', 'Pola 저는 ...입니다 adalah perkenalan formal yang sederhana.', 'The 저는 ...입니다 pattern is a simple formal introduction.', '저는 디온입니다.', 'Saya Dion.', 'I am Dion.', 13, 1),
  ('c2i-2', 'c-2-intro', 'sentence', '제 이름은 민지예요', 'je ireumeun minjiyeyo', 'Nama saya Minji.', 'My name is Minji.', '제 terdengar seperti "je", bukan "je-i".', '제 is one syllable, pronounced "je".', '제 berarti "milik saya" dalam bentuk sopan.', '제 is the polite form of "my".', '제 이름은 수진이에요.', 'Nama saya Sujin.', 'My name is Sujin.', NULL, 2),
  ('c2i-3', 'c-2-intro', 'word', '친구', 'chingu', 'Teman', 'Friend', 'ㄱ di tengah kata terdengar lebih dekat ke g.', 'The ㄱ in the middle sounds closer to g.', 'Kata benda umum untuk teman tanpa membedakan gender.', 'A common noun for a friend of any gender.', '민수는 제 친구예요.', 'Minsu adalah teman saya.', 'Minsu is my friend.', 6, 3),

  ('c3q-1', 'c-3-questions', 'sentence', '이름이 뭐예요?', 'ireumi mwoyeyo', 'Siapa namamu?', 'What is your name?', '뭐예요 mengalir sebagai mwo-ye-yo.', '뭐예요 flows as mwo-ye-yo.', 'Gunakan nama + 이/가 뭐예요? untuk menanyakan sesuatu.', 'Use noun + 이/가 뭐예요? to ask about something.', '이거 뭐예요?', 'Apa ini?', 'What is this?', NULL, 1),
  ('c3q-2', 'c-3-questions', 'sentence', '어디에 가요?', 'eodie gayo', 'Kamu pergi ke mana?', 'Where are you going?', '에 melekat pada 어디: eo-di-e.', 'Attach 에 to 어디: eo-di-e.', '어디에 가요? adalah pertanyaan sopan tentang tujuan.', '어디에 가요? is a polite question about a destination.', '학교에 가요.', 'Saya pergi ke sekolah.', 'I go to school.', NULL, 2),
  ('c3q-3', 'c-3-questions', 'sentence', '뭘 좋아해요?', 'mwol joahaeyo', 'Apa yang kamu suka?', 'What do you like?', '뭘 adalah bentuk pendek dari 무엇을.', '뭘 is a shortened form of 무엇을.', 'Gunakan 뭘 좋아해요? untuk menanyakan kesukaan.', 'Use 뭘 좋아해요? to ask about preferences.', '음악을 좋아해요.', 'Saya suka musik.', 'I like music.', NULL, 3),

  ('c4l-1', 'c-4-likes', 'sentence', '저는 음악을 좋아해요', 'jeoneun eumageul joahaeyo', 'Saya suka musik.', 'I like music.', '좋아해요 dibaca jo-a-hae-yo dengan empat ketukan ringan.', 'Read 좋아해요 as jo-a-hae-yo with four light beats.', 'Gunakan kata benda + 을/를 + 좋아해요 untuk menyatakan kesukaan.', 'Use noun + 을/를 + 좋아해요 to express a preference.', '저는 한국어를 좋아해요.', 'Saya suka Bahasa Korea.', 'I like Korean.', 16, 1),
  ('c4l-2', 'c-4-likes', 'sentence', '저는 커피를 안 좋아해요', 'jeoneun keopireul an joahaeyo', 'Saya tidak suka kopi.', 'I do not like coffee.', '안 diucapkan singkat tepat sebelum 좋아해요.', 'Say 안 briefly right before 좋아해요.', 'Letakkan 안 sebelum 좋아해요 untuk negasi sederhana.', 'Place 안 before 좋아해요 for simple negation.', '저는 매운 음식을 안 좋아해요.', 'Saya tidak suka makanan pedas.', 'I do not like spicy food.', NULL, 2),
  ('c4l-3', 'c-4-likes', 'sentence', '김치를 제일 좋아해요', 'gimchireul jeil joahaeyo', 'Saya paling suka kimchi.', 'I like kimchi the most.', '제일 berarti "paling".', '제일 means "the most".', 'Gunakan 제일 sebelum kata kerja untuk menekankan kesukaan.', 'Use 제일 before a verb to emphasize a preference.', '한국어를 제일 좋아해요.', 'Saya paling suka bahasa Korea.', 'I like Korean the most.', NULL, 3),

  ('c5d-1', 'c-5-dialogue', 'sentence', '안녕하세요! 만나서 반가워요.', 'annyeonghaseyo! mannaseo bangawoyo.', 'Halo! Senang bertemu dengan Anda.', 'Hello! Nice to meet you.', 'Ucapkan salam dulu, lalu sapa perkenalan.', 'Say the greeting first, then the meeting phrase.', 'Gabungkan salam dan ungkapan perkenalan dalam satu sapaan.', 'Combine the greeting and the meeting phrase in one exchange.', '안녕하세요! 저는 디온이에요.', 'Halo! Saya Dion.', 'Hello! I am Dion.', NULL, 1),
  ('c5d-2', 'c-5-dialogue', 'sentence', '저는 민지예요. 이름이 뭐예요?', 'jeoneun minjiyeyo. ireumi mwoyeyo', 'Saya Minji. Siapa namamu?', 'I am Minji. What is your name?', 'Perkenalkan nama, lalu balas dengan pertanyaan.', 'Introduce your name, then ask back.', 'Pola perkenalan singkat diikuti pertanyaan nama.', 'A short introduction followed by a name question.', '저는 수진이에요. 이름이 뭐예요?', 'Saya Sujin. Siapa namamu?', 'I am Sujin. What is your name?', NULL, 2),
  ('c5d-3', 'c-5-dialogue', 'sentence', '저는 디온이에요. 음악을 좋아해요.', 'jeoneun dionieyo. eumageul joahaeyo', 'Saya Dion. Saya suka musik.', 'I am Dion. I like music.', 'Kenalkan diri, lalu sebutkan kesukaanmu.', 'Introduce yourself, then share a preference.', 'Perkenalan singkat diikuti ungkapan kesukaan.', 'A short introduction followed by a preference.', '저는 민지예요. 영화를 좋아해요.', 'Saya Minji. Saya suka film.', 'I am Minji. I like movies.', NULL, 3),

  ('frv-1', 'f-remediation-vowels', 'character', 'ㅓ', 'eo', 'Vokal "eo" lagi', 'The vowel "eo" again', 'Buka rahang rileks; bunyinya di antara "o" dan "a".', 'Relax your jaw; the sound sits between "o" and "a".', 'Jangan bingung dengan ㅏ yang lebih terbuka.', 'Do not confuse it with the more open ㅏ.', '거 · 너 · 더', 'geo, neo, deo', 'geo, neo, deo', NULL, 1),
  ('frv-2', 'f-remediation-vowels', 'character', 'ㅡ', 'eu', 'Vokal "eu" lagi', 'The vowel "eu" again', 'Ratakan bibir dan tarik bunyi ke belakang mulut.', 'Flatten your lips and pull the sound back.', 'Berbeda dari ㅜ yang bibirnya bulat.', 'It differs from ㅜ, which rounds the lips.', '그 · 느 · 드', 'geu, neu, deu', 'geu, neu, deu', NULL, 2),

  ('frc1-1', 'f-remediation-consonants-1', 'character', 'ㄱ', 'g/k', 'Konsonan g/k lagi', 'The g/k consonant again', 'Di awal terdengar g lembut, di akhir k pendek.', 'Light g at the start, short k at the end.', 'Perhatikan posisinya dalam suku kata.', 'Notice its position within the syllable.', '가 · 국', 'ga, guk', 'ga, guk', NULL, 1),
  ('frc1-2', 'f-remediation-consonants-1', 'character', 'ㅅ', 's', 'Konsonan s lagi', 'The s consonant again', 'Di depan ㅣ mendekati "sy".', 'Before ㅣ it is closer to "sh".', 'Bandingkan 사 dan 시.', 'Compare 사 and 시.', '사 · 시', 'sa, si', 'sa, si', NULL, 2),

  ('frc2-1', 'f-remediation-consonants-2', 'character', 'ㄷ', 'd/t', 'Konsonan d/t lagi', 'The d/t consonant again', 'Di awal d ringan, di akhir t pendek.', 'Light d at the start, short t at the end.', 'Bandingkan dengan ㅌ yang berhembus.', 'Compare with ㅌ, which is aspirated.', '다 · 닫', 'da, dat', 'da, dat', NULL, 1),
  ('frc2-2', 'f-remediation-consonants-2', 'character', 'ㅂ', 'b/p', 'Konsonan b/p lagi', 'The b/p consonant again', 'Di awal b lembut, batchim p pendek.', 'Soft b at the start, short p as batchim.', 'Bandingkan dengan ㅍ yang berhembus.', 'Compare with ㅍ, which is aspirated.', '바 · 밥', 'ba, bap', 'ba, bap', NULL, 2),

  ('frb-1', 'f-remediation-batchim', 'word', '집', 'jip', 'Rumah', 'Home', 'Batchim ㅂ di akhir dilepas seperti p pendek.', 'Final ㅂ is released like a short p.', 'ㅈ dan ㅣ membentuk ji, lalu ㅂ menjadi batchim.', 'ㅈ and ㅣ form ji, then ㅂ becomes the batchim.', '집에 가요.', 'Saya pulang.', 'I go home.', 9, 1),
  ('frb-2', 'f-remediation-batchim', 'word', '강', 'gang', 'Sungai', 'River', 'ㅇ di akhir berbunyi ng.', 'Final ㅇ sounds like ng.', 'ㅇ diam di awal, tetapi ng di akhir.', 'ㅇ is silent at the start but ng at the end.', '강을 건너요.', 'Saya menyeberangi sungai.', 'I cross the river.', NULL, 2),

  ('frf-1', 'f-remediation-fluency', 'word', '물', 'mul', 'Air', 'Water', 'Gabungkan ㅁ + ㅜ + ㄹ menjadi satu blok.', 'Combine ㅁ + ㅜ + ㄹ into one block.', 'Baca bagian per bagian: m + u + l.', 'Read it in parts: m + u + l.', '물을 마셔요.', 'Saya minum air.', 'I drink water.', 7, 1),
  ('frf-2', 'f-remediation-fluency', 'word', '집', 'jip', 'Rumah', 'Home', 'Gabungkan ㅈ + ㅣ + ㅂ menjadi satu blok.', 'Combine ㅈ + ㅣ + ㅂ into one block.', 'Baca bagian per bagian: j + i + p.', 'Read it in parts: j + i + p.', '집에 가요.', 'Saya pulang.', 'I go home.', 9, 2),

  ('c6r-1', 'c-6-remediation', 'word', '안녕히 가세요', 'annyeonghi gaseyo', 'Selamat jalan', 'Goodbye', 'ㅎ pada 안녕히 terdengar lembut dalam ucapan cepat.', 'The ㅎ in 안녕히 is light in quick speech.', 'Ucapkan kepada orang yang pergi ketika Anda tetap tinggal.', 'Say this to the person leaving when you are staying.', '내일 봐요. 안녕히 가세요!', 'Sampai besok. Selamat jalan!', 'See you tomorrow. Goodbye!', NULL, 1),
  ('c6r-2', 'c-6-remediation', 'word', '안녕히 계세요', 'annyeonghi gyeseyo', 'Selamat tinggal (tetaplah baik)', 'Goodbye (please stay well)', '계세요 diucapkan gye-se-yo.', 'Say 계세요 as gye-se-yo.', 'Ucapkan ketika Anda pergi dan orang lain tetap tinggal.', 'Say it when you leave and the other person stays.', '다음에 봐요. 안녕히 계세요!', 'Sampai jumpa lagi. Selamat tinggal!', 'See you later. Goodbye!', NULL, 2);

INSERT INTO curriculum_check_items (id, check_node_id, category, prompt_id, prompt_en, choices, answer, explanation_id, explanation_en, item_order) VALUES
  ('fcv-1', 'f-check-vowels', 'recognition', 'Manakah bentuk vokal "a"?', 'Which shape is the vowel "a"?', '[{"id":"a","label":"ㅏ"},{"id":"b","label":"ㅓ"},{"id":"c","label":"ㅗ"},{"id":"d","label":"ㅜ"}]', 'a', 'ㅏ adalah vokal dengan garis ke kanan.', 'ㅏ is the vowel whose stroke points right.', 1),
  ('fcv-2', 'f-check-vowels', 'recognition', 'Manakah bentuk vokal "eo"?', 'Which shape is the vowel "eo"?', '[{"id":"a","label":"ㅏ"},{"id":"b","label":"ㅓ"},{"id":"c","label":"ㅣ"},{"id":"d","label":"ㅡ"}]', 'b', 'ㅓ adalah vokal dengan garis ke kiri.', 'ㅓ is the vowel whose stroke points left.', 2),
  ('fcv-3', 'f-check-vowels', 'sound', 'Bunyi apakah ㅜ?', 'What sound does ㅜ make?', '[{"id":"a","label":"o"},{"id":"b","label":"u"},{"id":"c","label":"eu"},{"id":"d","label":"i"}]', 'b', 'ㅜ berbunyi seperti "u" atau "oo".', 'ㅜ sounds like "u" or "oo".', 3),
  ('fcv-4', 'f-check-vowels', 'sound', 'Bunyi apakah ㅡ?', 'What sound does ㅡ make?', '[{"id":"a","label":"a"},{"id":"b","label":"eo"},{"id":"c","label":"eu"},{"id":"d","label":"u"}]', 'c', 'ㅡ berbunyi "eu" dengan bibir rata.', 'ㅡ sounds like "eu" with flat lips.', 4),

  ('fcc1-1', 'f-check-consonants-1', 'recognition', 'Konsonan "n" adalah?', 'Which consonant is "n"?', '[{"id":"a","label":"ㄱ"},{"id":"b","label":"ㄴ"},{"id":"c","label":"ㅁ"},{"id":"d","label":"ㅅ"}]', 'b', 'ㄴ berbunyi n.', 'ㄴ sounds like n.', 1),
  ('fcc1-2', 'f-check-consonants-1', 'recognition', 'Konsonan "m" adalah?', 'Which consonant is "m"?', '[{"id":"a","label":"ㄱ"},{"id":"b","label":"ㄴ"},{"id":"c","label":"ㅁ"},{"id":"d","label":"ㅅ"}]', 'c', 'ㅁ berbunyi m.', 'ㅁ sounds like m.', 2),
  ('fcc1-3', 'f-check-consonants-1', 'sound', 'Bunyi ㄱ di awal kata?', 'What sound does ㄱ make at the start?', '[{"id":"a","label":"g"},{"id":"b","label":"k"},{"id":"c","label":"n"},{"id":"d","label":"s"}]', 'a', 'Di awal, ㄱ terdengar seperti g lembut.', 'At the start, ㄱ sounds like a light g.', 3),
  ('fcc1-4', 'f-check-consonants-1', 'sound', 'Bunyi ㅅ di awal kata?', 'What sound does ㅅ make at the start?', '[{"id":"a","label":"s"},{"id":"b","label":"n"},{"id":"c","label":"m"},{"id":"d","label":"h"}]', 'a', 'Di awal, ㅅ terdengar seperti s.', 'At the start, ㅅ sounds like s.', 4),

  ('fcc2-1', 'f-check-consonants-2', 'recognition', 'Konsonan "b/p" adalah?', 'Which consonant is "b/p"?', '[{"id":"a","label":"ㄷ"},{"id":"b","label":"ㄹ"},{"id":"c","label":"ㅂ"},{"id":"d","label":"ㅇ"}]', 'c', 'ㅂ berbunyi b/p.', 'ㅂ sounds like b/p.', 1),
  ('fcc2-2', 'f-check-consonants-2', 'recognition', 'Konsonan yang diam di awal dan ng di akhir adalah?', 'Which consonant is silent at the start and ng at the end?', '[{"id":"a","label":"ㅇ"},{"id":"b","label":"ㅎ"},{"id":"c","label":"ㄷ"},{"id":"d","label":"ㅈ"}]', 'a', 'ㅇ diam di awal dan berbunyi ng di akhir.', 'ㅇ is silent at the start and ng at the end.', 2),
  ('fcc2-3', 'f-check-consonants-2', 'sound', 'Bunyi ㄹ di antara vokal?', 'What sound does ㄹ make between vowels?', '[{"id":"a","label":"r"},{"id":"b","label":"l"},{"id":"c","label":"m"},{"id":"d","label":"n"}]', 'a', 'Di antara vokal, ㄹ terdengar seperti r ringan.', 'Between vowels, ㄹ sounds like a light r.', 3),
  ('fcc2-4', 'f-check-consonants-2', 'sound', 'Bunyi ㅎ?', 'What sound does ㅎ make?', '[{"id":"a","label":"h"},{"id":"b","label":"k"},{"id":"c","label":"t"},{"id":"d","label":"p"}]', 'a', 'ㅎ berbunyi h dengan hembusan ringan.', 'ㅎ sounds like h with a light breath.', 4),

  ('fcb-1', 'f-check-batchim', 'syllable', 'Apa bunyi akhir pada 물?', 'What is the final sound in 물?', '[{"id":"a","label":"l"},{"id":"b","label":"m"},{"id":"c","label":"n"},{"id":"d","label":"ng"}]', 'a', 'ㄹ di akhir berbunyi l.', 'Final ㄹ sounds like l.', 1),
  ('fcb-2', 'f-check-batchim', 'syllable', 'Apa bunyi akhir pada 집?', 'What is the final sound in 집?', '[{"id":"a","label":"p"},{"id":"b","label":"b"},{"id":"c","label":"m"},{"id":"d","label":"ng"}]', 'a', 'ㅂ di akhir berbunyi p pendek.', 'Final ㅂ sounds like a short p.', 2),
  ('fcb-3', 'f-check-batchim', 'syllable', 'Apa bunyi akhir pada 한?', 'What is the final sound in 한?', '[{"id":"a","label":"n"},{"id":"b","label":"l"},{"id":"c","label":"m"},{"id":"d","label":"ng"}]', 'a', 'ㄴ di akhir berbunyi n.', 'Final ㄴ sounds like n.', 3),
  ('fcb-4', 'f-check-batchim', 'reading', 'Bagaimana membaca 안녕?', 'How do you read 안녕?', '[{"id":"a","label":"annyeong"},{"id":"b","label":"annyeonghaseyo"},{"id":"c","label":"annyeongha"},{"id":"d","label":"anyeong"}]', 'a', '안녕 dibaca an-nyeong.', '안녕 is read an-nyeong.', 4),

  ('fcf-1', 'f-check-fluency', 'recognition', 'Pilih vokal "ㅑ"?', 'Pick the vowel "ㅑ"?', '[{"id":"a","label":"ㅏ"},{"id":"b","label":"ㅑ"},{"id":"c","label":"ㅓ"},{"id":"d","label":"ㅕ"}]', 'b', 'ㅑ adalah ㅏ dengan satu garis tambahan.', 'ㅑ is ㅏ with one extra stroke.', 1),
  ('fcf-2', 'f-check-fluency', 'recognition', 'Pilih konsonan "ㅈ"?', 'Pick the consonant "ㅈ"?', '[{"id":"a","label":"ㅅ"},{"id":"b","label":"ㅈ"},{"id":"c","label":"ㅊ"},{"id":"d","label":"ㅎ"}]', 'b', 'ㅈ berbunyi j.', 'ㅈ sounds like j.', 2),
  ('fcf-3', 'f-check-fluency', 'sound', 'Bunyi ㅛ?', 'What sound does ㅛ make?', '[{"id":"a","label":"yo"},{"id":"b","label":"yu"},{"id":"c","label":"o"},{"id":"d","label":"u"}]', 'a', 'ㅛ berbunyi yo.', 'ㅛ sounds like yo.', 3),
  ('fcf-4', 'f-check-fluency', 'sound', 'Bunyi ㅊ?', 'What sound does ㅊ make?', '[{"id":"a","label":"ch"},{"id":"b","label":"j"},{"id":"c","label":"k"},{"id":"d","label":"t"}]', 'a', 'ㅊ berbunyi ch.', 'ㅊ sounds like ch.', 4),
  ('fcf-5', 'f-check-fluency', 'syllable', 'Gabungkan ㄱ + ㅏ?', 'Combine ㄱ + ㅏ?', '[{"id":"a","label":"가"},{"id":"b","label":"나"},{"id":"c","label":"다"},{"id":"d","label":"거"}]', 'a', 'ㄱ + ㅏ menjadi 가.', 'ㄱ + ㅏ becomes 가.', 5),
  ('fcf-6', 'f-check-fluency', 'syllable', 'Gabungkan ㅁ + ㅜ + ㄹ?', 'Combine ㅁ + ㅜ + ㄹ?', '[{"id":"a","label":"물"},{"id":"b","label":"불"},{"id":"c","label":"술"},{"id":"d","label":"눈"}]', 'a', 'ㅁ + ㅜ + ㄹ menjadi 물.', 'ㅁ + ㅜ + ㄹ becomes 물.', 6),
  ('fcf-7', 'f-check-fluency', 'reading', 'Baca 물?', 'Read 물?', '[{"id":"a","label":"mul"},{"id":"b","label":"mal"},{"id":"c","label":"mur"},{"id":"d","label":"mil"}]', 'a', '물 dibaca mul.', '물 is read mul.', 7),
  ('fcf-8', 'f-check-fluency', 'reading', 'Baca 집?', 'Read 집?', '[{"id":"a","label":"jip"},{"id":"b","label":"jap"},{"id":"c","label":"jop"},{"id":"d","label":"jep"}]', 'a', '집 dibaca jip.', '집 is read jip.', 8),

  ('c6c-1', 'c-6-check', 'vocabulary', '"Halo" dalam bahasa Korea?', 'What is "Hello" in Korean?', '[{"id":"a","label":"안녕하세요"},{"id":"b","label":"감사합니다"},{"id":"c","label":"죄송합니다"},{"id":"d","label":"안녕히 가세요"}]', 'a', '안녕하세요 berarti halo.', '안녕하세요 means hello.', 1),
  ('c6c-2', 'c-6-check', 'vocabulary', '"Terima kasih" dalam bahasa Korea?', 'What is "Thank you" in Korean?', '[{"id":"a","label":"감사합니다"},{"id":"b","label":"안녕하세요"},{"id":"c","label":"반가워요"},{"id":"d","label":"괜찮아요"}]', 'a', '감사합니다 berarti terima kasih.', '감사합니다 means thank you.', 2),
  ('c6c-3', 'c-6-check', 'reading', 'Baca 만나서 반가워요?', 'Read 만나서 반가워요?', '[{"id":"a","label":"mannaseo bangawoyo"},{"id":"b","label":"mannaseo bangapseumnida"},{"id":"c","label":"manna bangawoyo"},{"id":"d","label":"mannaseo bangawayo"}]', 'a', '만나서 반가워요 dibaca mannaseo bangawoyo.', '만나서 반가워요 is read mannaseo bangawoyo.', 3),
  ('c6c-4', 'c-6-check', 'reading', 'Baca 저는 학생입니다?', 'Read 저는 학생입니다?', '[{"id":"a","label":"jeoneun haksaengimnida"},{"id":"b","label":"jeoneun haksaengiyeyo"},{"id":"c","label":"jeoneun haksaengieyo"},{"id":"d","label":"jeo haksaengimnida"}]', 'a', '저는 학생입니다 dibaca jeoneun haksaengimnida.', '저는 학생입니다 is read jeoneun haksaengimnida.', 4),
  ('c6c-5', 'c-6-check', 'listening', 'Ungkapan untuk berkenalan?', 'Which expression means nice to meet you?', '[{"id":"a","label":"만나서 반가워요"},{"id":"b","label":"안녕히 가세요"},{"id":"c","label":"잘 먹겠습니다"},{"id":"d","label":"다녀오겠습니다"}]', 'a', '만나서 반가워요 berarti senang bertemu.', '만나서 반가워요 means nice to meet you.', 5),
  ('c6c-6', 'c-6-check', 'listening', 'Ungkapan untuk orang yang pergi?', 'Which expression do you say when someone leaves?', '[{"id":"a","label":"안녕히 가세요"},{"id":"b","label":"안녕하세요"},{"id":"c","label":"안녕히 계세요"},{"id":"d","label":"만나서 반가워요"}]', 'a', '안녕히 가세요 diucapkan saat orang lain pergi.', '안녕히 가세요 is said when the other person leaves.', 6),
  ('c6c-7', 'c-6-check', 'sentence', 'Kalimat yang benar untuk "Saya suka musik"?', 'Which sentence means "I like music"?', '[{"id":"a","label":"저는 음악을 좋아해요"},{"id":"b","label":"저는 음악을 안 좋아해요"},{"id":"c","label":"저는 음악을 싫어해요"},{"id":"d","label":"저는 노래를 좋아해요"}]', 'a', '저는 음악을 좋아해요 berarti saya suka musik.', '저는 음악을 좋아해요 means I like music.', 7),
  ('c6c-8', 'c-6-check', 'sentence', 'Kalimat yang benar untuk "Nama saya Minji"?', 'Which sentence means "My name is Minji"?', '[{"id":"a","label":"제 이름은 민지예요"},{"id":"b","label":"저는 이름 민지예요"},{"id":"c","label":"제 이름 민지입니다"},{"id":"d","label":"저는 민지 이름이에요"}]', 'a', '제 이름은 민지예요 berarti nama saya Minji.', '제 이름은 민지예요 means my name is Minji.', 8);

INSERT INTO curriculum_practice_items (id, practice_node_id, exercise_kind, source_type, source_ref, item_order) VALUES
  ('cp1-1', 'c-1-practice', 'vocabulary', 'node_item', 'c1g-1', 1),
  ('cp1-2', 'c-1-practice', 'vocabulary', 'node_item', 'c1g-2', 2),
  ('cp2-1', 'c-2-practice', 'vocabulary', 'node_item', 'c2i-1', 1),
  ('cp2-2', 'c-2-practice', 'vocabulary', 'node_item', 'c2i-2', 2),
  ('cp3-1', 'c-3-practice', 'vocabulary', 'node_item', 'c3q-1', 1),
  ('cp3-2', 'c-3-practice', 'vocabulary', 'node_item', 'c3q-2', 2),
  ('cp4-1', 'c-4-practice', 'vocabulary', 'node_item', 'c4l-1', 1),
  ('cp4-2', 'c-4-practice', 'vocabulary', 'node_item', 'c4l-2', 2),
  ('cp5-1', 'c-5-practice', 'vocabulary', 'node_item', 'c5d-1', 1),
  ('cp5-2', 'c-5-practice', 'vocabulary', 'node_item', 'c5d-2', 2);

